# Structures analysis

Files:
- LTS_CONFCNT_ONLY.OUT : contains the classes and structures in terms of substituted atoms

In [1]:
import sys
sys.path.insert(1, '../../crystal-code-tools/crystal_functions/crystal_functions/')

from file_readwrite import Crystal_output, write_cry_properties, Crystal_input
from convert import cry_gui2pmg

from pymatgen.io.ase import AseAtomsAdaptor
from ase.visualize import view

from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np
import pandas as pd

In [2]:
path = '/Users/brunocamino/Desktop/Imperial/cmsg_icl/solid-solutions/data/'
file = 'LTS_CONFCNT_ONLY'

new_atom = 'Li'

### Read the structures from the output files and replace with new_atom
This cell generates the structures list. This contains all the 4023 structures as pymatgen structure objects

In [3]:
cry_output = Crystal_output(path+file)
cry_output.config_analysis()

original_structure = cry_gui2pmg(path+file)
structuress = []
ti_atoms = []
for substitutions in cry_output.atom_type2:
    new_structure = original_structure.copy()
    for i in substitutions:
        new_structure.replace(i-1,new_atom)
    structuress.append(new_structure)
    ti_atoms.append((np.array(cry_output.atom_type1[i])-1).tolist())



In [27]:
view(AseAtomsAdaptor().get_atoms(structures[2]))

<Popen: returncode: None args: ['/Users/brunocamino/miniconda3/envs/cc/bin/p...>

In [4]:
#All structures
structures = structuress

In [7]:
#Random structures
'''structures = []
ti_atoms = []
for i in np.random.choice(4022,size = 100, replace=False):
    structures.append(structuress[i])
    ti_atoms.append((np.array(cry_output.atom_type1[i])-1).tolist())'''

'structures = []\nti_atoms = []\nfor i in np.random.choice(4022,size = 100, replace=False):\n    structures.append(structuress[i])\n    ti_atoms.append((np.array(cry_output.atom_type1[i])-1).tolist())'

In [8]:
#First 100 structures
'''structures = []
ti_atoms = []
for i in range(100):
    structures.append(structuress[i])
    ti_atoms.append((np.array(cry_output.atom_type1[i])-1).tolist())'''

'structures = []\nti_atoms = []\nfor i in range(100):\n    structures.append(structuress[i])\n    ti_atoms.append((np.array(cry_output.atom_type1[i])-1).tolist())'

### Specific structures

In [74]:
layers = cry_gui2pmg('data/structures/Layers.f34')
ordered = cry_gui2pmg('data/structures/Ordered.f34')
dispersed = cry_gui2pmg('data/structures/Dispersed.f34')
structures = [dispersed,ordered,layers]
ti_atoms = []
for structure in structures:
    ti = []
    for i,atom in enumerate(structure.atomic_numbers):
        if atom == 22:
            ti.append(i)
    ti_atoms.append(ti)

### Space group

In [13]:
space_group = []
for structure in structures:
    space_group.append(SpacegroupAnalyzer(structure).get_space_group_number())

### Shells

In [24]:
shells = np.unique(np.round(structures[0].distance_matrix[0],decimals=6)).tolist()
shells

[0.0, 2.54275, 3.595992, 4.404172, 5.0855, 5.685762, 6.22844, 7.62825]

### Average Ti-Ti distance

In [21]:
average_ti = []
for n,structure in enumerate(structures):
    average = 0.
    for i in ti_atoms[n]:
        for j in ti_atoms[n]: 
            average += round(structure.sites[i].distance(structure.sites[j]),6) 
    average_ti.append(average/(len(ti_atoms)**2))

In [16]:
average_ti

[4.123533610766093,
 4.058534882179975,
 4.030314140366101,
 4.002093398552226,
 4.030314140366101,
 4.0953128689522185,
 4.095312868952218,
 4.067092127138343,
 4.002093398552226,
 3.8070972127938747,
 3.900316683193867,
 3.965315411779984,
 4.095312868952218,
 4.067092127138343,
 3.8070972127938747,
 3.900316683193867,
 4.067092127138343,
 3.8070972127938747,
 3.900316683193867,
 4.002093398552226,
 3.8070972127938747,
 3.900316683193867,
 3.965315411779984,
 3.900316683193867,
 3.965315411779984,
 4.0953128689522185,
 4.095312868952218,
 4.067092127138343,
 3.8070972127938747,
 3.900316683193867,
 4.067092127138343,
 4.002093398552226,
 3.8070972127938747,
 3.900316683193867,
 3.965315411779984,
 3.8070972127938747,
 3.965315411779984,
 3.900316683193867,
 3.965315411779984,
 4.002093398552226,
 3.8070972127938747,
 3.900316683193867,
 3.900316683193867,
 3.965315411779984,
 3.965315411779984,
 4.0953128689522185,
 4.095312868952218,
 4.067092127138343,
 3.8070972127938747,
 3.90031

### Average second coordination 
The number of Ti atoms in the second shell averaged over all Ti atoms

In [25]:
second_coord_sum = []
for n,structure in enumerate(structures):
    sum_coord = 0
    for i in ti_atoms[n]:
        for j in ti_atoms[n]:
            if round(structure.sites[i].distance(structure.sites[j]),6) == round(shells[2],6):
                sum_coord += 1
    second_coord_sum.append(sum_coord)
second_coord_average = (np.array(second_coord_sum)/len(ti_atoms[n])).tolist()


In [26]:
second_coord_average

[4.444444444444445,
 4.666666666666667,
 4.666666666666667,
 4.666666666666667,
 4.666666666666667,
 4.444444444444445,
 4.444444444444445,
 4.444444444444445,
 4.666666666666667,
 5.333333333333333,
 5.111111111111111,
 4.888888888888889,
 4.444444444444445,
 4.444444444444445,
 5.333333333333333,
 5.111111111111111,
 4.444444444444445,
 5.333333333333333,
 5.111111111111111,
 4.666666666666667,
 5.333333333333333,
 5.111111111111111,
 4.888888888888889,
 5.111111111111111,
 4.888888888888889,
 4.444444444444445,
 4.444444444444445,
 4.444444444444445,
 5.333333333333333,
 5.111111111111111,
 4.444444444444445,
 4.666666666666667,
 5.333333333333333,
 5.111111111111111,
 4.888888888888889,
 5.333333333333333,
 4.888888888888889,
 5.111111111111111,
 4.888888888888889,
 4.666666666666667,
 5.333333333333333,
 5.111111111111111,
 5.111111111111111,
 4.888888888888889,
 4.888888888888889,
 4.444444444444445,
 4.444444444444445,
 4.444444444444445,
 5.333333333333333,
 5.111111111111111,


In [27]:
np.unique(np.array(second_coord_average))

array([4.44444444, 4.66666667, 4.88888889, 5.11111111, 5.33333333])

### Average second and third coordination 
The number of Ti atoms in the second and third shells averaged over all Ti atoms

In [28]:
second_third_coord_sum = []
for n,structure in enumerate(structures):
    sum_coord = 0
    for i in ti_atoms[n]:
        for j in ti_atoms[n]:
            if round(structure.sites[i].distance(structure.sites[j]),6) == round(shells[2],6) or \
             round(structure.sites[i].distance(structure.sites[j]),6) == round(shells[4],6):
                sum_coord += 1
    second_third_coord_sum.append(sum_coord)       
second_third_coord_average = (np.array(second_third_coord_sum)/len(ti_atoms[n])).tolist()

In [29]:
np.unique(np.array(second_third_coord_average))

array([5.33333333, 5.55555556, 5.77777778, 6.        , 6.22222222,
       6.66666667])

### Max and min coordination & Ti distribution

#### Second shell

In [33]:
distribution_function = []
second_coord_max = []
second_coord_min = []
for n,structure in enumerate(structures[0:1]):
    distance = []
    distance_atoms = []
    for i in ti_atoms[n]:
        dist = 0
        dist_atom = []
        for j in ti_atoms[n]:
            if round(structure.sites[i].distance(structure.sites[j]),6) == round(shells[2],6):
                dist += 1
                dist_atom.append(j)
        distance_atoms.append(dist_atom)
        distance.append(dist)  
        max_coord_atoms = max(enumerate(distance_atoms), key = lambda tup: len(tup[1]))[1]
        atom_coords = []
        for atom in max_coord_atoms:
            atom_coords.append(structure.cart_coords[atom].tolist())
        second_coord_max.append(max(max_coord_atoms))
        second_coord_min.append(min(max_coord_atoms))
            
    #second_coord_sum.append(sum_coord)
#second_coord_average = (np.array(second_coord_sum)/len(ti_atoms[n])).tolist()

In [34]:
second_coord_max

[24, 24, 24, 24, 26, 26, 26, 26, 26]

In [79]:
#Old one
second_coord_max = []
second_coord_min = []
for n,structure in enumerate(structures[0:1]):
    sum_coord = []    
    for i in ti_atoms[n]:
        sum_coord_atom = 0
        for j in ti_atoms[n]:
            sum_coord_atom += (round(structure.distance_matrix[i][j],6) == round(shells[2],6))
        sum_coord.append(sum_coord_atom)
    second_coord_max.append(max(sum_coord))
    second_coord_min.append(min(sum_coord))

#### Fourth shell

In [ ]:
fourth_coord_max = []
for n,structure in enumerate(structures):
    sum_coord = []    
    for i in ti_atoms[n]:
        sum_coord_atom = 0
        for j in ti_atoms[n]:
            sum_coord_atom += (round(structure.distance_matrix[i][j],6) == round(shells[2],6))
            sum_coord_atom += (round(structure.distance_matrix[i][j],6) == round(shells[4],6))
        sum_coord.append(sum_coord_atom)
    fourth_coord_max.append(max(sum_coord))

### Square distance from center of mass

#### Cartesian coordinates

In [16]:
std = [] 
std_sum = []
std_std = []
for n,structure in enumerate(structures[0:10000]):
    ti_coord = []
    for i in ti_atoms[n]:
        ti_coord.append(structure.cart_coords[i].tolist())
    
    std.append(np.std(ti_coord,axis=0).tolist())
    std_sum.append(np.round(np.sum(ti_coord),6))
    std_std.append(np.std(np.std(ti_coord,axis=0)))
np.unique(std_std)
        

array([0.36488537, 0.37306871, 0.40047482, 0.44463808, 0.46387399,
       0.48123779, 0.49585539, 0.54092928, 0.55323722, 0.69852801])

#### Spherical coordinates

In [100]:
distribution_com = [] 
for n,structure in enumerate(structures[0:100]):
    ti_coord = []
    ti_coord_sph = []
    for i in ti_atoms[n]:
        ti_coord.append(structure.cart_coords[i].tolist())
    centroid = centroidnp(np.array(ti_coord))
    ti_coord = ti_coord - centroid
    for coord in ti_coord:
        ti_coord_sph.append(cart2sph(coord[0],coord[1],coord[2]))
    print(np.std(ti_coord_sph,axis=0))
        

[1.69438047 0.46872947 1.08773498]
[1.70164327 0.66511309 1.44476935]
[1.87435127 0.61040919 1.52925174]


### Distance periodic site

In [59]:
coordination = [] 
for n,structure in enumerate(structures):
    second_coord = 0
    for i in ti_atoms[n]:        
        for j in ti_atoms[n]:
            if i != j:
                if round(structure.sites[i].distance(structure.sites[j]),6) == round(shells[2],6):
                    second_coord += 1
    #coordination.append(second_coord/len(ti_atoms[n]))
    coordination.append(second_coord)
                
coordination      

[26, 32, 36]

### Scan along row

#### Shells

In [91]:
def cart2sph(x, y, z):
    hxy = np.hypot(x, y)
    r = np.hypot(hxy, z)
    el = np.arctan2(z, hxy)
    az = np.arctan2(y, x)
    if np.around(az,6) ==  np.around(2*np.pi,6) \
    or np.around(az,6) ==  -np.around(2*np.pi,6):
        az = 0.
    return [round(az,6), round(el,6), round(r,6)]

In [ ]:
def cart2cent2sph(atom,center):
    x = atom[0]-center[0]
    y = atom[1]-center[1]
    z = atom[2]-center[2]
    return cart2sph(x, y, z)

In [ ]:
def cart2sin(x, y, z):
    hxy = np.hypot(x, y)
    r = np.hypot(hxy, z)
    el = np.sin(np.arctan2(z, hxy))
    az = np.cos(np.arctan2(y, x))
    return [round(az,6), round(el,6), round(r,6)]

In [86]:
def centroidnp(arr):
    length = arr.shape[0]
    sum_x = np.sum(arr[:, 0])
    sum_y = np.sum(arr[:, 1])
    sum_z = np.sum(arr[:, 2])
    return np.array([sum_x/length, sum_y/length, sum_z/length])

In [ ]:
#Spherical coordinates
#Make sure there are no gaps even if they have the same polar and azimuthal coords
max_row = []
for n,structure in enumerate(structures[3000:3001]):
    for i in ti_atoms[n]:
        spherical_coord = []
        row = []
        for j in ti_atoms[n]:
            #print(i,j)
            center_cart = structure.cart_coords[j]-structure.cart_coords[i]
            spherical_coord.append(cart2sph(center_cart[0],center_cart[1],center_cart[2]))   
        spherical_coord = np.around(np.array(spherical_coord),6)
        #print(spherical_coord[:,0:1],spherical_coord[:,0:1]+np.pi)
        for el in spherical_coord:
            #print(el[0:3],spherical_coord[:,0:3])
            #print(spherical_coord[:,0:2] == el[0:2],np.sum(np.prod(spherical_coord[:,0:2] == el[0:2],axis=1)))
            #print(np.sum(np.multiply(spherical_coord[:,0] == el[0]+np.pi,spherical_coord[:,1] == -el[1])))
            row.append(np.sum(np.prod(spherical_coord[:,0:2] == el[0:2],axis=1)))#+
                 #np.sum(np.multiply(spherical_coord[:,0] == el[0]+np.pi,spherical_coord[:,1] == -el[1])))
    max_row.append(max(row)+1)       
       

In [ ]:
#Sinusoidal coordinates
max_row = []
for n,structure in enumerate(structures[3000:3001]):
    for i in ti_atoms[n]:
        spherical_coord = []
        row = []
        #print(i)
        for j in ti_atoms[n]:
            #print(i,j)
            center_cart = structure.cart_coords[j]-structure.cart_coords[i]
            spherical_coord.append(cart2sin(center_cart[0],center_cart[1],center_cart[2]))   
        spherical_coord = np.around(np.array(spherical_coord),6)
        #print(spherical_coord)
        for el in spherical_coord:
            #print(spherical_coord[:,0:3])
            #print(spherical_coord[:,0:2] == el[0:2],np.sum(np.prod(spherical_coord[:,0:2] == el[0:2],axis=1))) 
            row.append(np.sum(np.prod(spherical_coord[:,0:2] == el[0:2],axis=1))+
                 np.sum(np.prod(spherical_coord[:,0:2] == -el[0:2],axis=1)))
    max_row.append(max(row)+1)       
       

In [ ]:
#get neighbours
max_radius = max(np.sum(structure.lattice.matrix,axis=1))
for n,structure in enumerate(structures[0:1]):
    for i in ti_atoms[n]:
        #print(structure.get_neighbor_list(max_radius)[3])
        for neigh in structure.get_neighbors(structure.sites[i],max_radius):
            if neigh.as_dict()['species'][0]['element'] == 'Ti':
                
        #for j in ti_atoms[n]:
            #if i != j:
                #print(structure.get_neighbors(structure.sites[i],3.))
#len(structure.get_all_neighbors(10.)[0])

# Neighbour analysis and classification

In [ ]:
shells

In [ ]:
ti_neigh_list = []
for i,structure in enumerate(structures[0:1]):
    for ti_atom_1 in ti_atoms[i]:
        ti_neigh = []
        for ti_atom_2 in ti_atoms[i]:
            if structure.distance_matrix[ti_atom_1][ti_atom_2] - shells[2] < 0.001:
                ti_neigh.append(cart2cent2sph(structure.cart_coords[ti_atom_2],structure.cart_coords[ti_atom_1]))
        ti_neigh_list.append(ti_neigh)
ti_neigh_list

In [ ]:
structures[0]

In [ ]:
structures[0].distance_matrix

### Fourier transform

In [ ]:
ti_coord = []
for i in ti_atoms[0]:
    ti_coord.append(structures[0].sites[i].coords.tolist())
np.fft.fftn(np.array(ti_coord))

In [ ]:
df = pd.DataFrame(list(zip(space_group,average_ti,second_coord_sum,second_coord_max,fourth_coord_max)),
               columns =['Space Group','Average Ti distance','Sum second coord','Max second coord','Max fourth coord'])

df[df['Space Group'] == 1]
df